name: Build EduVault APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Build APK
        run: |
          mkdir buildsrc
          EduVault_Nokia_C22_FIX.zip -dbuildsrc
          cd buildsrc
          flutter create . --platforms=android
          flutter pub get
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: eduvault-apk
          path: buildsrc/build/app/outputs/flutter-apk/app-release.apk
