name: Build EduVault APK

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: |
          mkdir buildsrc
          unzip -q EduVault_Android_Build.zip -d buildsrc
          cd buildsrc
          flutter create . --platforms=android
          flutter pub get
          flutter build apk --release
